/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sisteminformasiakademik;

import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

public class FormNilai extends javax.swing.JFrame {

    public FormNilai() {
        initComponents();
        this.setLocationRelativeTo(null);
        tampilComboNIM();
        
        cmbSemester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));

        tblNilai.getModel().addTableModelListener(e -> {
            hitungIPS();
        });
    }

    private void tampilComboNIM() {
        try {
            Connection conn = Koneksi.getKoneksi();
            ResultSet res = conn.createStatement().executeQuery("SELECT nim FROM mahasiswa");
            cmbNIM.removeAllItems();
            while(res.next()) {
                cmbNIM.addItem(res.getString("nim"));
            }
        } catch (Exception e) {
            System.out.println("Error NIM: " + e.getMessage());
        }
} 
    private void hitungIPS() {
        try {
            double totalPoin = 0;
            int totalSKS = 0;
            for (int i = 0; i < tblNilai.getRowCount(); i++) {
                if (tblNilai.getValueAt(i, 2) != null && tblNilai.getValueAt(i, 3) != null) {
                    String nilaiHuruf = tblNilai.getValueAt(i, 3).toString().trim().toUpperCase();
                    if (nilaiHuruf.isEmpty()) continue;
                    
                    int sks = Integer.parseInt(tblNilai.getValueAt(i, 2).toString());
                    int bobot = (nilaiHuruf.equals("A"))?4:(nilaiHuruf.equals("B"))?3:(nilaiHuruf.equals("C"))?2:(nilaiHuruf.equals("D"))?1:0;
                    
                    totalPoin += (sks * bobot);
                    totalSKS += sks;
                }
            }
            if (totalSKS > 0) lblIPS.setText(String.format("%.2f", totalPoin / totalSKS));
        } catch (Exception e) {
            System.out.println("Error Hitung: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbNIM = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbSemester = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNilai = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        lblIPS = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("TABEL NILAI");

        jLabel2.setText("NIM");

        cmbNIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNIMActionPerformed(evt);
            }
        });

        jLabel3.setText("Nama");

        jLabel4.setText("Semester");

        cmbSemester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2.3.4", "5", "6", "7", "8" }));
        cmbSemester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSemesterActionPerformed(evt);
            }
        });

        tblNilai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Kode MK", "Nama", "SKS", "Nilai"
            }
        ));
        jScrollPane1.setViewportView(tblNilai);

        jLabel5.setText("IPS");

        lblIPS.setText("0");

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbNIM, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(lblIPS))
                    .addComponent(btnSimpan))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblIPS))
                        .addGap(6, 6, 6)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(cmbSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSimpan)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        try {
        Connection conn = Koneksi.getKoneksi();
        for (int i = 0; i < tblNilai.getRowCount(); i++) {
            String kodeMK = tblNilai.getValueAt(i, 0).toString();
            String huruf = tblNilai.getValueAt(i, 3).toString();
            
            int bobot = 0;
    if (huruf.equalsIgnoreCase("A")) bobot = 4;
    else if (huruf.equalsIgnoreCase("B")) bobot = 3;
    else if (huruf.equalsIgnoreCase("C")) bobot = 2;
    else if (huruf.equalsIgnoreCase("D")) bobot = 1;
    else bobot = 0;

            String sql = "INSERT INTO nilai (nim, kode_mk, semester, nilai_huruf, bobot) VALUES (?,?,?,?,?)";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, cmbNIM.getSelectedItem().toString());
            pst.setString(2, kodeMK);
            pst.setString(3, cmbSemester.getSelectedItem().toString());
            pst.setString(4, huruf);
            pst.setInt(5, bobot);
            pst.executeUpdate();
        }
        JOptionPane.showMessageDialog(null, "Nilai Berhasil Disimpan!");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void cmbNIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNIMActionPerformed
        // TODO add your handling code here:
        try {
            DefaultTableModel model = (DefaultTableModel) tblNilai.getModel();
            model.setRowCount(0); 
            
            Connection conn = Koneksi.getKoneksi();
            ResultSet rsMhs = conn.createStatement().executeQuery("SELECT nama FROM mahasiswa WHERE nim='" + cmbNIM.getSelectedItem() + "'");
            if(rsMhs.next()) txtNama.setText(rsMhs.getString("nama"));

            String sql = "SELECT krs.kode_mk, matakuliah.nama_mk, matakuliah.sks FROM krs " +
             "INNER JOIN matakuliah ON krs.kode_mk = matakuliah.kode_mk " +
             "WHERE krs.nim='" + cmbNIM.getSelectedItem() + "' " +
             "AND krs.semester='" + cmbSemester.getSelectedItem() + "'";
            
            ResultSet rsKrs = conn.createStatement().executeQuery(sql);
            while(rsKrs.next()) {
                model.addRow(new Object[]{rsKrs.getString(1), rsKrs.getString(2), rsKrs.getString(3), ""});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    
    }//GEN-LAST:event_cmbNIMActionPerformed

    private void cmbSemesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSemesterActionPerformed
        // TODO add your handling code here:
       cmbNIMActionPerformed(null);
    }//GEN-LAST:event_cmbSemesterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new FormNilai().setVisible(true);
        }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cmbNIM;
    private javax.swing.JComboBox<String> cmbSemester;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIPS;
    private javax.swing.JTable tblNilai;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables
}
